//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinutoSeguros.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinutoSeguros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema de comunicação:
        ///O servidor pode estar indisponível ou existe um problema com sua conexão..
        /// </summary>
        internal static string ConectionErrorMessage {
            get {
                return ResourceManager.GetString("ConectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///à
        ///adeus
        ///agora
        ///aí
        ///ainda
        ///além
        ///algo
        ///algumas
        ///alguns
        ///ali
        ///ano
        ///anos
        ///antes
        ///ao
        ///aos
        ///apenas
        ///apoio
        ///após
        ///aquela
        ///aquelas
        ///aquele
        ///aqueles
        ///aqui
        ///aquilo
        ///área
        ///as
        ///às
        ///assim
        ///até
        ///atrás
        ///através
        ///baixo
        ///bastante
        ///bem
        ///boa
        ///boas
        ///bom
        ///bons
        ///breve
        ///cá
        ///cada
        ///catorze
        ///cedo
        ///cento
        ///certamente
        ///certeza
        ///cima
        ///cinco
        ///coisa
        ///com
        ///como
        ///conselho
        ///contra
        ///custa
        ///da
        ///dá
        ///dão
        ///daquela
        ///daquelas
        ///daquele
        ///daqueles
        ///dar
        ///das
        ///de
        ///debaixo
        ///demais
        ///dentro
        ///depois
        ///desde
        ///dessa
        ///dessas
        ///desse
        ///desses
        ///desta
        ///destas        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PortugueseStopWords {
            get {
                return ResourceManager.GetString("PortugueseStopWords", resourceCulture);
            }
        }
    }
}
